// Conventional OLL sequences from the CubeSkills reference; face-turn equivalents.
// Frozen fixtures end with an oriented upper layer that still needs PLL.
export const OLL_CATALOG = [
  {
    id: "OLL1",
    number: 1,
    group: "dot",
    referenceAlgorithm: "R U2 R2 F R F' U2 R' F R F'",
    algorithm: "R U2 R2 F R F' U2 R' F R F'",
    facelets: "BFFBURRLRUUURRRRRRFUBFFFFFFDDDDDDDDDUUULLLLLLLULBBBBBB",
  },
  {
    id: "OLL2",
    number: 2,
    group: "dot",
    referenceAlgorithm: "F R U R' U' F' f R U R' U' f'",
    algorithm: "F R U R' U' F' B U L U' L' B'",
    facelets: "BFRBURFLRFUBRRRRRRLUUFFFFFFDDDDDDDDDUUULLLLLLUULBBBBBB",
  },
  {
    id: "OLL3",
    number: 3,
    group: "dot",
    referenceAlgorithm: "f R U R' U' f' U' F R U R' U' F'",
    algorithm: "B U L U' L' B' U' F R U R' U' F'",
    facelets: "BBRFURLLUFUURRRRRRBULFFFFFFDDDDDDDDDRUULLLLLLFUUBBBBBB",
  },
  {
    id: "OLL4",
    number: 4,
    group: "dot",
    referenceAlgorithm: "f R U R' U' f' U F R U R' U' F'",
    algorithm: "B U L U' L' B' U F R U R' U' F'",
    facelets: "LFUBULFRRUUBRRRRRRUUBFFFFFFDDDDDDDDDUURLLLLLLLUFBBBBBB",
  },
  {
    id: "OLL5",
    number: 5,
    group: "angle",
    referenceAlgorithm: "r' U2 R U R' U r",
    algorithm: "L' B2 R B R' B L",
    facelets: "RLFBUUBUULFURRRRRRRRBFFFFFFDDDDDDDDDFUULLLLLLLUUBBBBBB",
  },
  {
    id: "OLL6",
    number: 6,
    group: "angle",
    referenceAlgorithm: "r U2 R' U' R U' r'",
    algorithm: "L F2 R' F' R F' L'",
    facelets: "FUURUURLBUFLRRRRRRUULFFFFFFDDDDDDDDDUUBLLLLLLFBRBBBBBB",
  },
  {
    id: "OLL7",
    number: 7,
    group: "angle",
    referenceAlgorithm: "r U R' U R U2 r'",
    algorithm: "L F R' F R F2 L'",
    facelets: "RUFUURUFLBUURRRRRRBUUFFFFFFDDDDDDDDDFLRLLLLLLLBUBBBBBB",
  },
  {
    id: "OLL8",
    number: 8,
    group: "angle",
    referenceAlgorithm: "r' U' R U' R' U2 r",
    algorithm: "L' B' R B' R' B2 L",
    facelets: "UFLUUBRUBUUFRRRRRRURLFFFFFFDDDDDDDDDRLBLLLLLLUUFBBBBBB",
  },
  {
    id: "OLL9",
    number: 9,
    group: "angle",
    referenceAlgorithm: "R U R' U' R' F R2 U R' U' F'",
    algorithm: "R U R' U' R' F R2 U R' U' F'",
    facelets: "FURUURBBUFUBRRRRRRUULFFFFFFDDDDDDDDDUFLLLLLLLULRBBBBBB",
  },
  {
    id: "OLL10",
    number: 10,
    group: "angle",
    referenceAlgorithm: "R U R' U R' F R F' R U2 R'",
    algorithm: "R U R' U R' F R F' R U2 R'",
    facelets: "BBUUULRUFLUBRRRRRRFRUFFFFFFDDDDDDDDDRFULLLLLLLUUBBBBBB",
  },
  {
    id: "OLL11",
    number: 11,
    group: "angle",
    referenceAlgorithm: "r' R2 U R' U R U2 R' U M'",
    algorithm: "L' R2 B R' B R B2 R' B R L' R L' R L'",
    facelets: "FFLBUUUUBRLURRRRRRRRUFFFFFFDDDDDDDDDLUFLLLLLLBUUBBBBBB",
  },
  {
    id: "OLL12",
    number: 12,
    group: "angle",
    referenceAlgorithm: "M' R' U' R U' R' U2 R U' M",
    algorithm: "R L' R L' R L' R' F' R F' R' F2 R F' R L'",
    facelets: "UUFRUUBFLULRRRRRRRUUFFFFFFFDDDDDDDDDBULLLLLLLUBRBBBBBB",
  },
  {
    id: "OLL13",
    number: 13,
    group: "line",
    referenceAlgorithm: "r U' r' U' r U r' y' R' U R",
    algorithm: "L F' L' U' L F L' F' U F",
    facelets: "RRLUUUUFBRLURRRRRRFUUFFFFFFDDDDDDDDDFBLLLLLLLBUUBBBBBB",
  },
  {
    id: "OLL14",
    number: 14,
    group: "line",
    referenceAlgorithm: "R' F R U R' F' R F U' F'",
    algorithm: "R' F R U R' F' R F U' F'",
    facelets: "RRLUUUBLURBFRRRRRRUUFFFFFFFDDDDDDDDDUFLLLLLLLUUBBBBBBB",
  },
  {
    id: "OLL15",
    number: 15,
    group: "line",
    referenceAlgorithm: "r' U' r R' U' R U r' U r",
    algorithm: "L' B' L R' U' R U L' B L",
    facelets: "RLFUUUBBULRURRRRRRRUBFFFFFFDDDDDDDDDFFULLLLLLLUUBBBBBB",
  },
  {
    id: "OLL16",
    number: 16,
    group: "line",
    referenceAlgorithm: "r U r' R U R' U' r U' r'",
    algorithm: "L F L' R U R' U' L F' L'",
    facelets: "FRUUUURLBUBLRRRRRRUULFFFFFFDDDDDDDDDUFBLLLLLLFURBBBBBB",
  },
  {
    id: "OLL17",
    number: 17,
    group: "dot",
    referenceAlgorithm: "R U R' U R' F R F' U2 R' F R F'",
    algorithm: "R U R' U R' F R F' U2 R' F R F'",
    facelets: "UBFRUFFLULURRRRRRRLUBFFFFFFDDDDDDDDDBUULLLLLLUURBBBBBB",
  },
  {
    id: "OLL18",
    number: 18,
    group: "dot",
    referenceAlgorithm: "y R U2 R2 F R F' U2 M' U R U' r'",
    algorithm: "B U2 B2 R B R' U2 B F' B F' B F' R B R' F'",
    facelets: "ULURUBBFBRUFRRRRRRUUUFFFFFFDDDDDDDDDFULLLLLLLRULBBBBBB",
  },
  {
    id: "OLL19",
    number: 19,
    group: "dot",
    referenceAlgorithm: "M U R U R' U' M' R' F R F'",
    algorithm: "R L' B R B R' B' R L' R L' R L' R' F R F'",
    facelets: "UFURUBFLRUUFRRRRRRLUBFFFFFFDDDDDDDDDLUULLLLLLRUBBBBBBB",
  },
  {
    id: "OLL20",
    number: 20,
    group: "dot",
    referenceAlgorithm: "M U R U R' U' M2 U R U' r'",
    algorithm: "R L' B R B R' B' R L' R L' F R F' L'",
    facelets: "UFURUBULUFUFRRRRRRLULFFFFFFDDDDDDDDDBUBLLLLLLRURBBBBBB",
  },
  {
    id: "OLL21",
    number: 21,
    group: "cross",
    referenceAlgorithm: "R U2 R' U' R U R' U' R U' R'",
    algorithm: "R U2 R' U' R U R' U' R U' R'",
    facelets: "LURUUULURFBBRRRRRRURUFFFFFFDDDDDDDDDBLFLLLLLLUFUBBBBBB",
  },
  {
    id: "OLL22",
    number: 22,
    group: "cross",
    referenceAlgorithm: "R U2 R2 U' R2 U' R2 U2 R",
    algorithm: "R U2 R2 U' R2 U' R2 U2 R",
    facelets: "FULUUUBULBLFRRRRRRRBUFFFFFFDDDDDDDDDURULLLLLLUFRBBBBBB",
  },
  {
    id: "OLL23",
    number: 23,
    group: "cross",
    referenceAlgorithm: "R2 D R' U2 R D' R' U2 R'",
    algorithm: "R2 D R' U2 R D' R' U2 R'",
    facelets: "UUUUUURUFLLFRRRRRRURUFFFFFFDDDDDDDDDLFBLLLLLLRBBBBBBBB",
  },
  {
    id: "OLL24",
    number: 24,
    group: "cross",
    referenceAlgorithm: "r U R' U' r' F R F'",
    algorithm: "L F R' F' L' F R F'",
    facelets: "FUUUUURUURLBRRRRRRURFFFFFFFDDDDDDDDDLFBLLLLLLLBUBBBBBB",
  },
  {
    id: "OLL25",
    number: 25,
    group: "cross",
    referenceAlgorithm: "y F' r U R' U' r' F R",
    algorithm: "R' F R B' R' F' R B",
    facelets: "UULUUURUURLURRRRRRURFFFFFFFDDDDDDDDDFFBLLLLLLBBLBBBBBB",
  },
  {
    id: "OLL26",
    number: 26,
    group: "cross",
    referenceAlgorithm: "R U2 R' U' R U' R'",
    algorithm: "R U2 R' U' R U' R'",
    facelets: "FUUUUURUBUFLRRRRRRURLFFFFFFDDDDDDDDDUBBLLLLLLFLRBBBBBB",
  },
  {
    id: "OLL27",
    number: 27,
    group: "cross",
    referenceAlgorithm: "R U R' U R U2 R'",
    algorithm: "R U R' U R U2 R'",
    facelets: "RUFUUUUULBBURRRRRRBRUFFFFFFDDDDDDDDDFLRLLLLLLLFUBBBBBB",
  },
  {
    id: "OLL28",
    number: 28,
    group: "angle",
    referenceAlgorithm: "r U R' U' M U R U' R'",
    algorithm: "L F R' F' R L' U R U' R'",
    facelets: "UUUUURUBURURRRRRRRFUFFFFFFFDDDDDDDDDLFLLLLLLLBLBBBBBBB",
  },
  {
    id: "OLL29",
    number: 29,
    group: "angle",
    referenceAlgorithm: "y R U R' U' R U' R' F' U' F R U R'",
    algorithm: "B U B' U' B U' B' R' U' R B U B'",
    facelets: "ULUUUBBUBUUFRRRRRRRRLFFFFFFDDDDDDDDDFFULLLLLLRULBBBBBB",
  },
  {
    id: "OLL30",
    number: 30,
    group: "angle",
    referenceAlgorithm: "y' F U R U2 R' U' R U2 R' U' F'",
    algorithm: "L U F U2 F' U' F U2 F' U' L'",
    facelets: "UULBUUUFLBRFRRRRRRRUUFFFFFFDDDDDDDDDBUFLLLLLLULRBBBBBB",
  },
  {
    id: "OLL31",
    number: 31,
    group: "angle",
    referenceAlgorithm: "R' U' F U R U' R' F' R",
    algorithm: "R' U' F U R U' R' F' R",
    facelets: "BUUBUULRURLBRRRRRRUUFFFFFFFDDDDDDDDDRUFLLLLLLLFUBBBBBB",
  },
  {
    id: "OLL32",
    number: 32,
    group: "angle",
    referenceAlgorithm: "R U B' U' R' U R B R'",
    algorithm: "R U B' U' R' U R B R'",
    facelets: "LBURUUFUUFLRRRRRRRUFLFFFFFFDDDDDDDDDBURLLLLLLBUUBBBBBB",
  },
  {
    id: "OLL33",
    number: 33,
    group: "line",
    referenceAlgorithm: "R U R' U' R' F R F'",
    algorithm: "R U R' U' R' F R F'",
    facelets: "FRUUUURLURBBRRRRRRUUFFFFFFFDDDDDDDDDLFBLLLLLLLUUBBBBBB",
  },
  {
    id: "OLL34",
    number: 34,
    group: "line",
    referenceAlgorithm: "R U R2 U' R' F R U R U' F'",
    algorithm: "R U R2 U' R' F R U R U' F'",
    facelets: "RRFUUUULURBURRRRRRLUFFFFFFFDDDDDDDDDUFBLLLLLLLUBBBBBBB",
  },
  {
    id: "OLL35",
    number: 35,
    group: "angle",
    referenceAlgorithm: "R U2 R2 F R F' R U2 R'",
    algorithm: "R U2 R2 F R F' R U2 R'",
    facelets: "ULRBUUBUUBFURRRRRRURRFFFFFFDDDDDDDDDFULLLLLLLFULBBBBBB",
  },
  {
    id: "OLL36",
    number: 36,
    group: "angle",
    referenceAlgorithm: "R' U' R U' R' U R U l U' R' U x",
    algorithm: "R' U' R U' R' U R U R B' R' B",
    facelets: "ULLUUBRUURUURRRRRRUFFFFFFFFDDDDDDDDDFRBLLLLLLBULBBBBBB",
  },
  {
    id: "OLL37",
    number: 37,
    group: "angle",
    referenceAlgorithm: "F R U' R' U' R U R' F'",
    algorithm: "F R U' R' U' R U R' F'",
    facelets: "UUFUURBBUBUURRRRRRUURFFFFFFDDDDDDDDDRLLLLLLLLLFFBBBBBB",
  },
  {
    id: "OLL38",
    number: 38,
    group: "angle",
    referenceAlgorithm: "R U R' U R U' R' U' R' F R F'",
    algorithm: "R U R' U R U' R' U' R' F R F'",
    facelets: "RUUUURULLUURRRRRRRLUFFFFFFFDDDDDDDDDFBBLLLLLLBFUBBBBBB",
  },
  {
    id: "OLL39",
    number: 39,
    group: "line",
    referenceAlgorithm: "L F' L' U' L U F U' L'",
    algorithm: "L F' L' U' L U F U' L'",
    facelets: "BLUUUUURFUBBRRRRRRFURFFFFFFDDDDDDDDDRFLLLLLLLLUUBBBBBB",
  },
  {
    id: "OLL40",
    number: 40,
    group: "line",
    referenceAlgorithm: "R' F R U R' U' F' U R",
    algorithm: "R' F R U R' U' F' U R",
    facelets: "UFBUUUFRURLLRRRRRRLUFFFFFFFDDDDDDDDDBBULLLLLLUURBBBBBB",
  },
  {
    id: "OLL41",
    number: 41,
    group: "angle",
    referenceAlgorithm: "R U R' U R U2 R' F R U R' U' F'",
    algorithm: "R U R' U R U2 R' F R U R' U' F'",
    facelets: "FUFUURULUBURRRRRRRLURFFFFFFDDDDDDDDDLBBLLLLLLUFUBBBBBB",
  },
  {
    id: "OLL42",
    number: 42,
    group: "angle",
    referenceAlgorithm: "R' U' R U' R' U2 R F R U R' U' F'",
    algorithm: "R' U' R U' R' U2 R F R U R' U' F'",
    facelets: "URUUULBUBRUFRRRRRRUFUFFFFFFDDDDDDDDDFBLLLLLLLRULBBBBBB",
  },
  {
    id: "OLL43",
    number: 43,
    group: "angle",
    referenceAlgorithm: "y R' U' F' U F R",
    algorithm: "B' U' R' U R B",
    facelets: "URLUUBUULUUURRRRRRRLFFFFFFFDDDDDDDDDBFFLLLLLLBURBBBBBB",
  },
  {
    id: "OLL44",
    number: 44,
    group: "angle",
    referenceAlgorithm: "f R U R' U' f'",
    algorithm: "B U L U' L' B'",
    facelets: "RRUBUURUUFLBRRRRRRFFLFFFFFFDDDDDDDDDUUULLLLLLLUBBBBBBB",
  },
  {
    id: "OLL45",
    number: 45,
    group: "line",
    referenceAlgorithm: "F R U R' U' F'",
    algorithm: "F R U R' U' F'",
    facelets: "RRUUUURLUFBBRRRRRRFULFFFFFFDDDDDDDDDUFULLLLLLLUBBBBBBB",
  },
  {
    id: "OLL46",
    number: 46,
    group: "line",
    referenceAlgorithm: "R' U' R' F R F' U R",
    algorithm: "R' U' R' F R F' U R",
    facelets: "UULRUFUULUUURRRRRRRLFFFFFFFDDDDDDDDDBUFLLLLLLBBRBBBBBB",
  },
  {
    id: "OLL47",
    number: 47,
    group: "angle",
    referenceAlgorithm: "F' L' U' L U L' U' L U F",
    algorithm: "F' L' U' L U L' U' L U F",
    facelets: "LUBRUULBFULURRRRRRUURFFFFFFDDDDDDDDDBUFLLLLLLRFUBBBBBB",
  },
  {
    id: "OLL48",
    number: 48,
    group: "angle",
    referenceAlgorithm: "F R U R' U' R U R' U' F'",
    algorithm: "F R U R' U' R U R' U' F'",
    facelets: "BURUURFBRFUBRRRRRRLUUFFFFFFDDDDDDDDDUFULLLLLLULLBBBBBB",
  },
  {
    id: "OLL49",
    number: 49,
    group: "angle",
    referenceAlgorithm: "r U' r2 U r2 U r2 U' r",
    algorithm: "L F' L2 B L2 F L2 B' L",
    facelets: "FULBUUBFLBLFRRRRRRRUUFFFFFFDDDDDDDDDUUULLLLLLURRBBBBBB",
  },
  {
    id: "OLL50",
    number: 50,
    group: "angle",
    referenceAlgorithm: "r' U r2 U' r2 U' r2 U r'",
    algorithm: "L' B L2 F' L2 B' L2 F L'",
    facelets: "FFLRUUBULBLFRRRRRRRBUFFFFFFDDDDDDDDDUUULLLLLLUURBBBBBB",
  },
  {
    id: "OLL51",
    number: 51,
    group: "line",
    referenceAlgorithm: "f R U R' U' R U R' U' f'",
    algorithm: "B U L U' L' U L U' L' B'",
    facelets: "BFRUUUFBRFLBRRRRRRLUUFFFFFFDDDDDDDDDURULLLLLLUULBBBBBB",
  },
  {
    id: "OLL52",
    number: 52,
    group: "line",
    referenceAlgorithm: "R' U' R U' R' U y' R' U R B",
    algorithm: "R' U' R U' R' U F' U F R",
    facelets: "BULFULFULUUURRRRRRURFFFFFFFDDDDDDDDDRURLLLLLLBBUBBBBBB",
  },
  {
    id: "OLL53",
    number: 53,
    group: "angle",
    referenceAlgorithm: "r' U' R U' R' U R U' R' U2 r",
    algorithm: "L' B' R B' R' B R B' R' B2 L",
    facelets: "BLBBUUFUFUFURRRRRRLRRFFFFFFDDDDDDDDDUUULLLLLLRULBBBBBB",
  },
  {
    id: "OLL54",
    number: 54,
    group: "angle",
    referenceAlgorithm: "r U R' U R U' R' U R U2 r'",
    algorithm: "L F R' F R F' R' F R F2 L'",
    facelets: "BUBRUUFLFUFURRRRRRLURFFFFFFDDDDDDDDDUUULLLLLLRBLBBBBBB",
  },
  {
    id: "OLL55",
    number: 55,
    group: "line",
    referenceAlgorithm: "y R' F R U R U' R2 F' R2 U' R' U R U R'",
    algorithm: "B' R B U B U' B2 R' B2 U' B' U B U B'",
    facelets: "LULLUBRURUUURRRRRRFFBFFFFFFDDDDDDDDDUUULLLLLLBRFBBBBBB",
  },
  {
    id: "OLL56",
    number: 56,
    group: "line",
    referenceAlgorithm: "r' U' r U' R' U R U' R' U R r' U r",
    algorithm: "L' B' L U' R' U R U' R' U R L' B L",
    facelets: "BLBUUUFBFURURRRRRRLURFFFFFFDDDDDDDDDUFULLLLLLRULBBBBBB",
  },
  {
    id: "OLL57",
    number: 57,
    group: "line",
    referenceAlgorithm: "R U R' U' M' U R U' r'",
    algorithm: "R U R' U' R L' R L' R L' F R F' L'",
    facelets: "URUUUUULURBRRRRRRRFUFFFFFFFDDDDDDDDDLFLLLLLLLBUBBBBBBB",
  },
] as const;
