// Conventional PLL sequences checked against the CubeSkills reference.
// Face-turn adaptation; original reference notation retained for reproducibility.
export const PLL_CATALOG = [
  {
    id: "Ua",
    group: "edges",
    referenceAlgorithm: "R U' R U R U R U' R' U' R2",
    algorithm: "R U' R U R U R U' R' U' R2",
    facelets: "UUUUUUUUURLRRRRRRRFRFFFFFFFDDDDDDDDDLFLLLLLLLBBBBBBBBB",
  },
  {
    id: "Ub",
    group: "edges",
    referenceAlgorithm: "R2 U R U R' U' R' U' R' U R'",
    algorithm: "R2 U R U R' U' R' U' R' U R'",
    facelets: "UUUUUUUUURFRRRRRRRFLFFFFFFFDDDDDDDDDLRLLLLLLLBBBBBBBBB",
  },
  {
    id: "H",
    group: "edges",
    referenceAlgorithm: "M2 U M2 U2 M2 U M2",
    algorithm: "R L' R L' D R L' R L' U2 R L' R L' D R L' R L'",
    facelets: "UUUUUUUUURLRRRRRRRFBFFFFFFFDDDDDDDDDLRLLLLLLLBFBBBBBBB",
  },
  {
    id: "Z",
    group: "edges",
    referenceAlgorithm: "M2 U M2 U M' U2 M2 U2 M' U2",
    algorithm:
      "R L' R L' D R L' R L' U R L' R L' R L' F2 R L' R L' B2 R L' R L' R L' U2",
    facelets: "UUUUUUUUURFRRRRRRRFRFFFFFFFDDDDDDDDDLBLLLLLLLBLBBBBBBB",
  },
  {
    id: "Aa",
    group: "corners",
    referenceAlgorithm: "x R' U R' D2 R U' R' D2 R2 x'",
    algorithm: "R' F R' B2 R F' R' B2 R2",
    facelets: "UUUUUUUUULRFRRRRRRFFBFFFFFFDDDDDDDDDBLLLLLLLLRBRBBBBBB",
  },
  {
    id: "Ab",
    group: "corners",
    referenceAlgorithm: "x R2 D2 R U R' D2 R U' R x'",
    algorithm: "R2 B2 R F R' B2 R F' R",
    facelets: "UUUUUUUUUBRBRRRRRRFFRFFFFFFDDDDDDDDDRLLLLLLLLLBFBBBBBB",
  },
  {
    id: "E",
    group: "corners",
    referenceAlgorithm: "x' R U' R' D R U R' D' R U R' D R U' R' D' x",
    algorithm: "R B' R' F R B R' F' R B R' F R B' R' F'",
    facelets: "UUUUUUUUUBRFRRRRRRLFRFFFFFFDDDDDDDDDFLBLLLLLLRBLBBBBBB",
  },
  {
    id: "T",
    group: "adjacent",
    referenceAlgorithm: "R U R' U' R' F R2 U' R' U' R U R' F'",
    algorithm: "R U R' U' R' F R2 U' R' U' R U R' F'",
    facelets: "UUUUUUUUUBLFRRRRRRFFRFFFFFFDDDDDDDDDLRLLLLLLLRBBBBBBBB",
  },
  {
    id: "Jb",
    group: "adjacent",
    referenceAlgorithm: "R U R' F' R U R' U' R' F R2 U' R' U'",
    algorithm: "R U R' F' R U R' U' R' F R2 U' R' U'",
    facelets: "UUUUUUUUUBFFRRRRRRFRRFFFFFFDDDDDDDDDLLLLLLLLLRBBBBBBBB",
  },
  {
    id: "Ja",
    group: "adjacent",
    referenceAlgorithm: "R' U L' U2 R U' R' U2 R L U'",
    algorithm: "R' U L' U2 R U' R' U2 R L U'",
    facelets: "UUUUUUUUURRBRRRRRRFFFFFFFFFDDDDDDDDDBBLLLLLLLLLRBBBBBB",
  },
  {
    id: "Ra",
    group: "adjacent",
    referenceAlgorithm: "R U' R' U' R U R D R' U' R D' R' U2 R' U'",
    algorithm: "R U' R' U' R U R D R' U' R D' R' U2 R' U'",
    facelets: "UUUUUUUUUBRFRRRRRRFFRFFFFFFDDDDDDDDDLBLLLLLLLRLBBBBBBB",
  },
  {
    id: "Rb",
    group: "adjacent",
    referenceAlgorithm: "R' U2 R U2 R' F R U R' U' R' F' R2 U'",
    algorithm: "R' U2 R U2 R' F R U R' U' R' F' R2 U'",
    facelets: "UUUUUUUUURFBRRRRRRFRFFFFFFFDDDDDDDDDBLLLLLLLLLBRBBBBBB",
  },
  {
    id: "F",
    group: "adjacent",
    referenceAlgorithm: "R' U' F' R U R' U' R' F R2 U' R' U' R U R' U R",
    algorithm: "R' U' F' R U R' U' R' F R2 U' R' U' R U R' U R",
    facelets: "UUUUUUUUUBRFRRRRRRFBRFFFFFFDDDDDDDDDLLLLLLLLLRFBBBBBBB",
  },
  {
    id: "Y",
    group: "diagonal",
    referenceAlgorithm: "F R U' R' U' R U R' F' R U R' U' R' F R F'",
    algorithm: "F R U' R' U' R U R' F' R U R' U' R' F R F'",
    facelets: "UUUUUUUUULRRRRRRRRFFBFFFFFFDDDDDDDDDRBLLLLLLLBLFBBBBBB",
  },
  {
    id: "V",
    group: "diagonal",
    referenceAlgorithm: "R' U R' U' y R' F' R2 U' R' U R' F R F",
    algorithm: "R' U R' U' B' R' B2 U' B' U B' R B R",
    facelets: "UUUUUUUUULBRRRRRRRFFBFFFFFFDDDDDDDDDRLLLLLLLLBRFBBBBBB",
  },
  {
    id: "Na",
    group: "diagonal",
    referenceAlgorithm: "R U R' U R U R' F' R U R' U' R' F R2 U' R' U2 R U' R'",
    algorithm: "R U R' U R U R' F' R U R' U' R' F R2 U' R' U2 R U' R'",
    facelets: "UUUUUUUUURLLRRRRRRBFFFFFFFFDDDDDDDDDLRRLLLLLLFBBBBBBBB",
  },
  {
    id: "Nb",
    group: "diagonal",
    referenceAlgorithm: "R' U R U' R' F' U' F R U R' F R' F' R U' R",
    algorithm: "R' U R U' R' F' U' F R U R' F R' F' R U' R",
    facelets: "UUUUUUUUULLRRRRRRRFFBFFFFFFDDDDDDDDDRRLLLLLLLBBFBBBBBB",
  },
  {
    id: "Ga",
    group: "cycles",
    referenceAlgorithm: "R2 U R' U R' U' R U' R2 D U' R' U R D' U",
    algorithm: "R2 U R' U R' U' R U' R2 D U' R' U R D' U",
    facelets: "UUUUUUUUURBLRRRRRRLFFFFFFFFDDDDDDDDDBRBLLLLLLFLRBBBBBB",
  },
  {
    id: "Gb",
    group: "cycles",
    referenceAlgorithm: "y' D R' U' R U D' R2 U R' U R U' R U' R2 U'",
    algorithm: "D F' U' F U D' F2 U F' U F U' F U' F2 U'",
    facelets: "UUUUUUUUURLBRRRRRRBFFFFFFFFDDDDDDDDDFBRLLLLLLLRLBBBBBB",
  },
  {
    id: "Gc",
    group: "cycles",
    referenceAlgorithm: "R2 U' R U' R U R' U R2 D' U R U' R' D U'",
    algorithm: "R2 U' R U' R U R' U R2 D' U R U' R' D U'",
    facelets: "UUUUUUUUULFRRRRRRRRLBFFFFFFDDDDDDDDDFRFLLLLLLBBLBBBBBB",
  },
  {
    id: "Gd",
    group: "cycles",
    referenceAlgorithm: "D' R U R' U' D R2 U' R U' R' U R' U R2 U",
    algorithm: "D' R U R' U' D R2 U' R U' R' U R' U R2 U",
    facelets: "UUUUUUUUURRLRRRRRRLBFFFFFFFDDDDDDDDDBFBLLLLLLFLRBBBBBB",
  },
] as const;
